% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{siunitx}

    \newcolumntype{d}{S[
      table-align-text-before=false,
      table-align-text-after=false,
      input-symbols={-,\*+()}
    ]}
  
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\author{}
\date{\vspace{-2.5em}}

\begin{document}

\section{Introduction}\label{introduction}

L'activité d'assurance repose sur un mécanisme de production inversé :
l'assureur perçoit les primes avant de connaître avec certitude le
montant réel des dépenses qu'il devra engager. En effet, il est lié à
l'assuré par une promesse d'indemnisation en cas de réalisation du
risque couvert. Le maintien d'un tel système nécessite donc des
dispositifs de contrôle de la capacité des assureurs à honorer leurs
engagements. C'est dans cette perspective que s'inscrit le cadre
réglementaire de Solvabilité II, entré en vigueur en 2016, dont
l'objectif principal est de garantir que les compagnies d'assurance
disposent de fonds propres suffisants pour faire face à leurs
obligations et ainsi instaurer un climat de confiance entre assureurs et
assurés.

La solvabilité d'une compagnie d'assurance désigne sa capacité à
respecter ses engagements financiers à court, moyen et long terme,
notamment en matière de règlement des sinistres et de prestations
contractuelles. Elle constitue ainsi un indicateur fondamental de la
solidité financière des assureurs. Toutefois, cette solvabilité demeure
fortement influencée par l'environnement économique et financier. Par
exemple, une hausse du taux d'inflation peut entraîner une augmentation
mécanique du coût des sinistres, tandis qu'une variation des taux
d'intérêt affecte à la fois les perspectives de rendement des placements
financiers et la valorisation des obligations détenues par les
compagnies d'assurance.

Dans un contexte marqué par la volatilité des marchés financiers, les
risques de perturbation des chaînes de valeur économiques, ainsi que le
renforcement des exigences prudentielles, il devient essentiel de mieux
comprendre les déterminants de la solvabilité des entreprises
d'assurance. Cette problématique est d'autant plus importante que la
stabilité et la pérennité du secteur assurantiel en dépendent
directement.

Le présent travail a donc pour objectif d'évaluer l'impact des variables
financières et macroéconomiques sur la solvabilité des entreprises
d'assurance en France. Plus précisément, il s'agira d'identifier les
variables les plus significatives et de mesurer leur influence sur la
solidité financière des assureurs. La résolution de cette problématique
reposera sur la mobilisation d'outils économétriques appliqués à des
données financières, macroéconomiques et à des indicateurs de
solvabilité propres au secteur de l'assurance. Cette étude permettra
notamment d'apprécier le degré de dépendance de la solvabilité des
assureurs vis-à-vis des variables macro-financières.

\section{Revue de la littérature}\label{revue-de-la-littuxe9rature}

Les assureurs jouent un rôle majeur dans le système financier en tant
qu'investisseurs institutionnels et leur exposition aux différents
risques est structurante pour leur solvabilité. Dans le cadre prudentiel
Solvabilité II, la sensibilité des fonds propres aux variations des
taux, des marchés actions et plus généralement de la conjoncture
économique est fortement encadrée. Cette revue de littérature vise à
synthétiser les principaux résultats existants.

\subsection{Impact des taux d'intérêt et du marché obligataire sur la
solvabilité des
assureurs}\label{impact-des-taux-dintuxe9ruxeat-et-du-marchuxe9-obligataire-sur-la-solvabilituxe9-des-assureurs}

La longue durée des engagements d'assurance rend ces entreprises
particulièrement sensibles à la structure par terme des taux. Les stress
tests réalisés par l'EIOPA mettent en évidence une forte sensibilité des
entreprises européennes d'assurance aux chocs de marché, révélant
l'exposition directe du SCR aux variations de taux. L'environnement
prolongé de taux bas a exercé une pression sur la solvabilité et la
rentabilité des assureurs notamment à travers leurs fonds propres. La
réévaluation des primes de risques suite à la remontée des taux peut
ainsi entraîner des pertes importantes dans les portefeuilles
obligataires, affectant le ratio de solvabilité (EIOPA, 2018) {[}1{]}.
Dans le cadre de Solvabilité II, la courbe des taux sans risque utilisée
pour actualiser les flux futurs constitue un élément central dans le
calcul des provisions Best Estimates. Un abaissement durable de cette
courbe entraîne une hausse des provisions, particulièrement pour les
passifs de longue duration, ce qui réduit mécaniquement les fonds
propres disponibles (Aalala, 2021) {[}7{]}. Par ailleurs, Berdin et
Gründl (2015) {[}2{]} montrent qu'un environnement de faibles taux peut
conduire les assureurs à accroître leur exposition à des actifs plus
risqués afin de compenser la faiblesse des rendements. Cette
réallocation accroît la sensibilité du bilan aux variations de taux
d'intérêt. Ces travaux confirment que la gestion actif-passif et la
duration des portefeuilles constituent des éléments centraux dans la
maîtrise du risque de solvabilité. Enfin, Poufinas et Siopi (2024)
{[}3{]} mettent en évidence une relation inverse entre le développement
du marché obligataire et le ratio de solvabilité. Un marché obligataire
plus développé se caractérise par une meilleure liquidité et une
meilleure stabilité, conduisant à une hausse de la demande en
obligations et accroit leur prix. Cette appréciation de la valeur des
obligations peut accroître l'exposition au risque de crédit et de
spread, augmentant ainsi le capital réglementaire requis.

\#\#Impact du marché actions, de la volatilité et des corrélations de
marché

L'exposition des compagnies d'assurance au marché actions s'est accrue
dans un contexte de hausse des taux et d'inflation élevée. Face à cette
remontée des taux, l'EIOPA observe une réallocation partielle des
portefeuilles vers des actifs plus risqués, notamment les actions, afin
de préserver le rendement, au prix d'un besoin accru en capital
réglementaire. Les travaux de Baranoff et Sager (2002) {[}11{]} montrent
qu'une exposition accrue aux risques financiers, notamment actions,
crédit et taux, s'accompagne d'un niveau de capital requis plus élevé
afin d'absorber la volatilité des marchés. Les fluctuations de la valeur
de marché affectent directement les fonds propres et introduisent une
volatilité significative dans le ratio de solvabilité (Rapport ACM 2023)
{[}6{]}. Dans cette logique, les travaux de Pénasse et Dezorme (2021)
{[}5{]} mettent en évidence un arbitrage entre le rendement espéré des
actions et le surplus de SCR imposé par Solvabilité II.

\subsection{Rôle des variables macroéconomiques : inflation et cycle
économique}\label{ruxf4le-des-variables-macrouxe9conomiques-inflation-et-cycle-uxe9conomique}

Au-delà des variables financières, la littérature souligne que la
conjoncture macroéconomique, notamment l'inflation et la croissance,
exerce un effet significatif sur la solvabilité des assureurs via la
profitabilité, le niveau des sinistres et la dynamique des primes. Les
travaux récents de l'EIOPA montrent que l'inflation exerce une pression
négative sur la valeur réelle et le rendement des actifs non indexés
ainsi que sur la rentabilité des assureurs. Pour les assureurs non-vie,
elle augmente également le coût des sinistres et des charges
d'exploitation. Pour les assureurs vie, une inflation inattendue peut
rendre les provisions techniques insuffisantes et dégrader la
rentabilité technique, ce qui exerce une pression négative sur la
solvabilité (EIOPA, 2023) {[}9{]}. L'étude de Gonji et al.~(2020)
{[}10{]} met également en évidence un impact du taux d'inflation et du
PIB sur la croissance et la rentabilité des compagnies d'assurance. Une
croissance économique soutenue favorise généralement la demande
d'assurance et la capacité des assureurs à générer des fonds propres,
tandis qu'un ralentissement économique peut dégrader la qualité des
actifs et peser sur le ratio de solvabilité.

Dans l'ensemble, la littérature met en évidence le rôle central des
variables macro-financières dans la dynamique de solvabilité, avec des
effets différenciés selon les branches. Les assureurs Vie apparaissent
généralement plus sensibles aux taux et aux marchés financiers en raison
de la longue duration de leurs engagements, tandis que la branche
Non-Vie semble davantage influencée par l'inflation et le cycle
d'exploitation. Notre travail s'inscrit dans cette lignée tout en s'en
distinguant sur plusieurs points. D'une part, nous mobilisons des
données Solvabilité II françaises sur la période 2016-2025 ce qui permet
de travailler dans un cadre réglementaire homogène peu exploité
empiriquement. D'autre part, nous combinons deux approches
complémentaires --- modèle en différences et ARDL --- afin de capter
simultanément les dynamiques de court terme, les relations d'équilibre
de long terme et l'hétérogénéité individuelle des assureurs. Enfin, la
distinction systématique entre branches Vie et Non-Vie constitue un
apport empirique par rapport aux études qui traitent le secteur de façon
agrégée.

\section{Chronologie des évènements en
France}\label{chronologie-des-uxe9vuxe8nements-en-france}

Nous avons réalisé une chronologie des évènements macroéconomiques et
macro-financiers entre 2016 et 2025 (période de nos données) ayant
impacté la solvabilité et l'activité des assureurs. Cela a permis de
déceler les variables pertinentes pour notre analyse et afin de déceler
des premiers mécanismes dans l'évolution et la sensibilité du ratio de
solvabilité aux variables macro-financières. Nous avons relevé trois
grandes phases économiques sur cette période. De 2016 à 2020, les
assureurs étaient placés dans un environnement de taux d'intérêt très
bas qui a exercé une pression négative sur leur ratio de solvabilité. En
effet, les revenus obligataires étaient faibles, ce qui a dégradé leur
portefeuille d'investissement et il a été plus difficile pour les
assureurs vie d'honorer leurs engagements. Suite à cela, l'économie a
subi un retournement et un choc inflationniste pendant les années 2021
et 2022 dû à la reprise économique post-COVID-19 et la crise
énergétique. Les taux d'intérêt directeurs de la BCE ont rapidement
augmenté et l'inflation a explosé. Pour les assureurs, la hausse brutale
des taux a entraîné des pertes latentes sur leur portefeuille
obligataire, entraînant une baisse des fonds propres et donc une
dégradation du ratio de solvabilité. Enfin, durant les dernières années
2023 à 2025, l'économie traverse une période d'instabilité financière et
géopolitique. Les marchés financiers sont affectés par plusieurs sources
de volatilité, notamment une crise bancaire et des tensions
géopolitiques toujours dans un contexte inflationniste et de taux
d'intérêt élevés. Les portefeuilles des compagnies d'assurance ont perdu
en valeur et le SCR de marché a augmenté, détériorant les deux
composants du ratio de solvabilité.

Cette chronologie nous a permis de noter les variables macro-économiques
qui semblent en grande partie impacter la solvabilité et l'activité des
assureurs. Ainsi, il a été observé que les taux d'intérêt ont un impact
sur la valeur des obligations détenues par les assureurs entrainant des
pertes ou plus-values latentes réduisant la valeur de marché de leurs
fonds propres. En outre, la rentabilité des portefeuilles obligataires
des assureurs est affectée. Dans ce contexte, les assureurs doivent
ajuster la duration de leur portefeuille afin de gérer leur exposition
au risque de taux. Ces éléments impactent donc le ratio de solvabilité
des assureurs. L'inflation impacte elle aussi significativement
l'activité des assureurs, à travers une hausse du coût des sinistres
pour les assureurs non-vie qui amène les assureurs à ajuster leur
tarification et réévaluer leurs provisions à la hausse. L'inflation a
conduit alors une baisse de leur résultat technique et leur solvabilité
est dégradée. Enfin, la volatilité des marchés financiers entraîne une
baisse potentielle de la valeur des portefeuilles actions des assureurs
et une augmentation du SCR de marché pour couvrir cette incertitude.
Cette combinaison réduit les fonds propres et peut dégrader le ratio de
solvabilité.

\section{Statistiques descriptives}\label{statistiques-descriptives}

\subsection{Analyse univariée}\label{analyse-univariuxe9e}

Cette section est consacrée à l'analyse univariée des variables, visant
à décrire leurs distributions et leurs principales caractéristiques
statistiques.

\subsubsection{Répartition des compagnies selon leur
nature}\label{ruxe9partition-des-compagnies-selon-leur-nature}

L'activité d'assurance non-vie concentre la majorité des compagnies du
marché. À l'inverse, les Fonds de Retraite et de Prévoyance Sociale
(FRPS) demeurent très faiblement représentés, avec une part limitée à
\(0,91 \%\). De même, le segment de la réassurance ne regroupe qu'une
fraction marginale des compagnies d'assurance, soit \(2,56 \%\).

\begin{center}\includegraphics[width=0.6\linewidth]{Stat_desc_files/figure-latex/unnamed-chunk-2-1} \end{center}

\subsubsection{Répartition des compagnies par
famille}\label{ruxe9partition-des-compagnies-par-famille}

La répartition par famille montre que les entresprises dans notre base
sont majoritairement les organismes mutualistes, lesquels représentent
\(53,71 \%\) de l'ensemble des compagnies. Les bancassureurs et les
assureurs traditionnels représentant chacun approximativemen \(23\%\).

\begin{center}\includegraphics[width=0.6\linewidth]{Stat_desc_files/figure-latex/unnamed-chunk-3-1} \end{center}

\subsection{Analyse bivarariée}\label{analyse-bivarariuxe9e}

À l'exception du segment de la réassurance, les organismes mutualistes
apparaissent comme majoritairement représentés dans l'ensemble des
regroupements par nature d'activité. Leur part relative demeure plus
élevée que celle des bancassureurs et des assureurs traditionnels, tant
dans les catégories des prestataires d'assurance non-vie que dans celles
de l'assurance vie et de la capitalisation. En revanche, le secteur de
la réassurance est dominé par les assureurs traditionnels, lesquels
représentent \(71,7\%\) des acteurs recensés. Il convient également de
souligner que seuls les organismes mutualistes et les assureurs
traditionnels interviennent dans la fourniture de fonds de retraite et
de prévoyance sociale (FRSP). Enfin, la répartition des différentes
familles d'assureurs apparaît globalement équilibrée dans les activités
mixtes combinant assurance vie et assurance non-vie.

Dans un soucis d'avoir des données de taille comparable entre les
catégorie mixte, non-vie et vie, nous avons fusionné les catégories
mixte et vie.

\begin{center}\includegraphics[width=0.6\linewidth]{Stat_desc_files/figure-latex/unnamed-chunk-4-1} \end{center}

\subsection{Analyses trimestrielles}\label{analyses-trimestrielles}

Pour toutes les analyses qui suivent, nous ne prendrons en compte que
deux natures de sociétés:

\begin{itemize}
\tightlist
\item
  Non Vie;
\item
  Vie (regroupant les natures \textbf{Vie/Capitalisation} et
  \textbf{Mixte}).
\end{itemize}

La base de données contient 3444 trimestres avec des variables cibles
déclarées. Nous pouvons donc observer l'évolution moyenne des Fonds
propres et du ratio de solvabilité avec les données disponibles.

\begin{enumerate}
\def\labelenumi{(\roman{enumi})}
\tightlist
\item
  \textbf{Ratio de solvabilité}
\end{enumerate}

\begin{center}\includegraphics[width=0.6\linewidth]{Stat_desc_files/figure-latex/unnamed-chunk-5-1} \end{center}

Le ratio moyen de solvabilité trimestriel apporte plus d'information sur
les variations qu'ont connues les sociétés d'assurance au cours de
l'année. On constate donc que le ratio de solvabilité moyen des sociétés
oscille avec beaucoup plus d'amplitude que les données annuelles ne le
laissent entrevoir. Le ratio moyen trimestriel des sociétés Non Vie
varie avec une tendance légèrement baissière entre \textbf{320\(\%\)} et
\textbf{250\(\%\) }. Il y a également une volatilité qui est
décroissante dans le temps. Quant au ratio trimestriel moyen des
sociétés d'assurances Vie, il est globalement plus faible que celui des
sociétés non vie évoluant entre \textbf{160\(\%\)} et
\textbf{260\(\%\)}. Entre 2018 et 2020, on remarque une
désynchronisation très forte entre le ratio moyen annuel et trimestriel
des sociétés d'assurances vie.

\begin{enumerate}
\def\labelenumi{(\roman{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  \textbf{Fonds Propres}
\end{enumerate}

\begin{center}\includegraphics[width=0.6\linewidth]{Stat_desc_files/figure-latex/4-1} \end{center}

Les données trimestrielles offrent une vision plus détaillée de
l'évolution des fonds propres. Ces graphiques montrent que les fonds
propres des sociétés d'assurance Vie sont plus volatils que ceux des
sociétés Non‑Vie. Par ailleurs, les fonds propres moyens des sociétés
Vie et Non‑Vie semblent présenter une légère tendance haussière, ce qui
suggère que les entreprises de notre échantillon accumulent
progressivement davantage de fonds propres au fil du temps, malgré
certaines fluctuations.

Nous observons également un écart important entre les valeurs annuelles
et trimestrielles, aussi bien pour les sociétés d'assurance Non‑Vie que
pour les sociétés Vie. Ce biais pourrait provenir de la taille des
entreprises déclarant des données trimestrielles. En effet, toutes les
sociétés ne transmettent pas d'informations trimestrielles. Seules 131
sociétés de la base disposent d'au moins une observation trimestrielle,
ce qui représente environ 50.38\(\%\) de l'ensemble des sociétés
recensées.

\begin{center}\includegraphics[width=0.6\linewidth]{Stat_desc_files/figure-latex/Décalage-1} \end{center}

La divergence entre les moyennes annuelles et trimestrielles peut
s'expliquer par le fait que les sociétés ne déclarant pas de données
trimestrielles présentent, en moyenne, des niveaux de fonds propres
annuels plus faibles. Autrement dit, seules les grandes sociétés
d'assurance transmettent des données trimestrielles, tandis que toutes
les sociétés --- y compris les plus petites --- déclarent des données
annuelles. Ces petites sociétés tirent donc la moyenne annuelle globale
vers le bas, ce qui crée un écart entre les deux séries.

Pour corriger ce biais de sélection présent dans les données
trimestrielles, nous allons ajuster les séries trimestrielles à partir
des données annuelles.

\paragraph{Ajustement des valeurs
trimestrielles}\label{ajustement-des-valeurs-trimestrielles}

L'objectif est d'estimer le montant total de SCR et de fonds propres
trimestriels que nous aurions obtenu si toutes les sociétés avaient
transmis des valeurs trimestrielles. Pour cela, pour les sociétés ne
déclarant que des valeurs annuelles, nous estimerons leurs valeurs
trimestrielles en nous appuyant sur les comportements observés chez les
sociétés qui déclarent à la fois des données trimestrielles et
annuelles.

La méthode d'ajustement repose sur le calcul du taux de croissance moyen
par nature, obtenu à partir des sociétés qui déclarent à la fois des
valeurs annuelles et trimestrielles. Ces taux de croissance moyens
servent ensuite à estimer les valeurs trimestrielles manquantes à partir
des valeurs annuelles disponibles.

\begin{enumerate}
\def\labelenumi{(\roman{enumi})}
\tightlist
\item
  Pour le premier trimestre
\end{enumerate}

Le taux de croissance moyen utilisé pour l'ajsutement correspond au taux
de croissance entre la somme des valeurs de l'année précédente et la
somme des valeurs du premier trimestre de l'année suivante.

\begin{description}
\tightlist
\item[Supposons que nous souhaitons déterminer le taux de croissance
moyen du premier trimestre de l'année t. Pour cela, nous considèrons
l'ensemble E des sociétés ayant déclaré les valeurs de l'année t-1 ainsi
que celles du premier trimestre de l'année t. Le taux de croissanse se
calcul donc de la manière suivante :]
\end{description}

\[ \tau_{moyen_{1,t}} =   \frac{\sum_{j \in E} SCR^j_{T_{1,t}}-\sum_{j \in E} SCR^j_{A_{t-1}} }{\sum_{j \in E}SCR^j_{A_{t-1}}} \]
où :

\begin{itemize}
\tightlist
\item
  \(SCR^j_{T_{1,t}}\) désigne le SCR de la société j au premier
  trimestre de l'année t;
\item
  \(SCR^j_{A_{t-1}}\) désigne le SCR de la société j de l'année t-1.
\end{itemize}

Nous faisons l'hypothèse que les sociétés n'ayant pas déclaré le premier
trimestre de l'année t auraient connu un taux de croissance
\(\tau _{moyen_{1,t}}\) de leur SCR entre la fin de l'année t‑1 et le
premier trimestre de l'année t. Nous estimons donc le SCR des sociétés
n'ayant pas déclaré au premier trimestre de l'année t en multipliant la
somme de leur SCR de l'année t‑1 par \(1+\tau _{moyen_{1,t}}\). Pour
estimer le SCR moyen au premier trimestre de l'année t, il suffit alors
de considérer la somme des SCR des sociétés ayant déclaré, d'y ajouter
la somme estimée pour celles qui n'ont pas déclaré, puis de diviser
l'ensemble par le nombre total de sociétés.

\begin{enumerate}
\def\labelenumi{(\roman{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Pour les autres trimestres (T2, T3 et T4)
\end{enumerate}

Le taux de croissance moyen utilisé pour l'imputation correspond au taux
de croissance entre la somme des valeurs du trimestre précédent et la
somme des valeurs du trimestre que l'on souhaite estimer. Les valeurs
estimer du premier trimestre servent à estimer ceux du deuxième, les
valeurs de deuxième servent à estimer le troisième et les valeurs du
troisième servent à estimer ceux du quatrième.

Supposons que nous souhaitons déterminer le taux de croissance moyen du
trimestre i\(\in \{2,3,4\}\) de l'année t. Pour cela, nous considèrons
l'ensemble \(E'\) des sociétés ayant déclaré les valeurs aux trimestres
i-1 et i de l'année t. Le taux de croissanse se calcul donc de la
manière suivante :

\[ \tau_{moyen_{i,t}} =   \frac{\sum_{j \in E'} SCR^j_{T_{i,t}}-\sum_{j \in E'} SCR^j_{T_{i-1,t}} }{\sum_{j \in E'}SCR^j_{T_{i-1,t}}} \]
Nous estimons le SCR des sociétés n'ayant pas déclaré au trimestre i de
l'année t en multipliant l'estimation de leur SCR du trimestre i-1 de
l'année t par \(1+\tau _{moyen_{i,t}}\). Pour estimer le SCR moyen au
trimestre i de l'année t, il suffit alors de considérer la somme des SCR
des sociétés ayant déclaré, d'y ajouter la somme estimée pour celles qui
n'ont pas déclaré, puis de diviser l'ensemble par le nombre total de
sociétés.

\subsubsection{Visualisation de
l'ajustement}\label{visualisation-de-lajustement}

\begin{center}\includegraphics[width=0.6\linewidth]{Stat_desc_files/figure-latex/8-1} \end{center}

Après ajustement, on observe que les données trimestrielles s'alignent
désormais mieux avec les données annuelles, ce qui confirme la
correction du biais initialement identifié.

\section{Modélisation}\label{moduxe9lisation}

La complexité des interactions entre les variables macro-financières et
la solvabilité des assureurs nécessite une approche empirique
séquentielle. Notre stratégie de modélisation s'articule autour de trois
axes complémentaires :

\begin{enumerate}
  \item \textbf{}Modèle en données de panel : Cette première modélisation vise à analyser la dynamique globale des indicateurs de solvabilité tout en tenant compte de l'hétérogénéité individuelle des assureurs.
  \item \textbf{}Régressions en différence simple : Nous effectuons une régression MCO des différences logarithmiques en ne retenant que la dimension temporelle afin d'évaluer la dynamique de court terme.
  \item \textbf{}Modèle ARDL (Auto Regressive Distributed Lag) : Il permet d'intégrer simultanément des relations de court terme et d'éventuelles relations de long terme (cointégration) qui ne peuvent pas être captées par les modèles de régression simple.
\end{enumerate}

\subsection{Régressions en
différence}\label{ruxe9gressions-en-diffuxe9rence}

Les régressions en différence constituent étape d'analyse des liens de
court terme entre les variables macro-financières et les indicateurs de
solvabilité. Cette approche permet d'étudier la transmission immédiate
des chocs macro-financiers tout en intégrant une dynamique
autorégressive et d'éventuels effets retardés. Nous utilisons des
modèles de régression linéaire estimés par les Moindres Carrés
Ordinaires. La spécification générale du modèle est la suivante :

\begin{equation}
\Delta Y_t = \alpha + \sum_{i=1}^{n} \beta_i \Delta X_{i, t-k} + \rho \Delta Y_{t-1} + \epsilon_t
\end{equation}

Où :

\begin{itemize}
    \item $\Delta Y_t$ représente le taux de croissance de l'indicateur de solvabilité étudié (Ratio, Fonds Propres ou SCR) au temps $t$.
    \item $\alpha$ est la constante du modèle (ou drift).
    \item $\Delta X_{i, t-k}$ représente la variation de la $i$-ème variable explicative (Indices boursiers, IPC, Taux, PIB) avec un retard $k \geq 0$.
    \item $\rho$ est le coefficient associé au terme autorégressif, captant l'inertie de la variable expliquée.
    \item $\epsilon_t$ est le terme d'erreur (bruit blanc) $\epsilon_t \sim N(0, \sigma^2)$.
\end{itemize}

Ce modèle repose sur les hypothèses classiques des MCO : linéarité de la
relation, exogénéité des régresseurs, homoscédasticité et absence
d'autocorrélation des résidus, et normalité de la distribution des
erreurs. Ces hypothèses sont vérifiées empiriquement en fin de partie à
l'aide des tests appropriés.

\subsubsection{Agrégation et transformation des
données}\label{agruxe9gation-et-transformation-des-donnuxe9es}

Dans le cadre de cette modélisation, les données individuelles des
assureurs et les variables macro-financières ont été agrégées par
trimestre afin de ne conserver qu'une dimension temporelle. Cette
agrégation permet d'obtenir une série synthétique reflétant l'évolution
globale du secteur et de s'aligner sur les dates de reporting
réglementaires du secteur. Ce choix méthodologique implique dans un
premier temps de renoncer à l'analyse des effets individuels mais il est
cohérent avec l'objectif de l'étude, centré sur la dynamique
macroéconomique de la solvabilité.

Nous modéliserons les fonds propres, le SCR et le ratio de solvabilité
des assureurs. Nous avons retenu les variables explicatives suivantes
(valeurs trimestrielles) : les indices boursiers S\&P 500 et Euro Stoxx
50, les taux d'intérêt de court et long terme, l'indice des prix à la
consommation en France (IPC) et le Produit Intérieur Brut français.

Pour chaque indice boursier (S\&P 500, EURO STOXX 50, DAX, CAC 40), nous
effectuons deux transformations majeures pour assurer la pertinence de
l'analyse :

\begin{itemize}
  \item \textbf{Agrégation trimestrielle} : Afin de faire correspondre les données boursières aux dates de remise des rapports de solvabilité, nous retenons la dernière valeur de clôture enregistrée pour chaque trimestre.
  \item \textbf{Calcul des rendements logarithmiques} : Nous utilisons la formule $r_t = \ln(P_t) - \ln(P_{t-1})$. Les log-rendements sont préférés car ils permettent de traiter des séries temporelles stationnaires et facilitent la comparaison entre indices de niveaux de prix différents.
\end{itemize}

\subsubsection{Spécification des variables et
stationnarité}\label{spuxe9cification-des-variables-et-stationnarituxe9}

Nous avons également enrichi nos données en calculant les différences
logarithmiques des variables qui seront utilisées dans la régression en
différence. Cette transformation permet de rendre les séries
stationnaires et d'interpréter les variations comme des taux de
croissance. Les taux d'intérêt sont quant à eux exprimés en différences
premières, correspondant à des variations en niveau.

L'ensemble des variables sont transformées en différences logarithmiques
selon \(\Delta\ln(X_t) = \ln(X_t) - \ln(X_{t-1})\), à l'exception des
taux d'intérêt exprimés en différences premières
\(\Delta X_t = X_t - X_{t-1}\), ces derniers pouvant prendre des valeurs
négatives incompatibles avec le logarithme.

Afin de pouvoir mener des régressions robustes, il est nécessaire que
l'ensemble de nos séries utilisées soient stationnaires. La
stationnarité des séries transformées a été vérifiée à l'aide des tests
de Dickey-Fuller augmenté (ADF) et KPSS. Le test ADF repose ici sur
l'observation de la p-value associée au test :

\begin{itemize}
    \item $H_0$ : La série possède une racine unitaire (non-stationnaire)
    \item $H_1$  : La série est stationnaire
\end{itemize}

Si \(t_{stat}\) \textless{} \(t_{crit}\) : On rejette \emph{H0} au seuil
de significativité choisi.

Les hypothèses du test KPSS sont les suivantes :

\begin{itemize}
  \item $H_0$ : La série est stationnaire
  \item $H_1$ : La série est non stationnaire
\end{itemize}

Si \(t_{stat}\) \textgreater{} \(t_{crit}\) : On rejette \emph{H0} au
seuil de significativité choisi.

Ainsi, les tests ADF et KPSS appliqués aux séries transformées
confirment leur stationnarité validant les conditions d'application du
modèle de régression linéaire Moindres Carrés Ordinaires.

\subsubsection{Test de Causalité de
Granger}\label{test-de-causalituxe9-de-granger}

Des tests de causalité au sens de Granger ont été réalisés afin
d'identifier les retards pertinents des variables macro-financières dans
les modèles dynamiques. Les tests ont été conduits sur des horizons
allant de un à quatre trimestres afin de capturer d'éventuels délais de
transmission. L'hypothèse nulle du test est la suivante :

\emph{H0} : les coefficients associés aux valeurs retardées de la
variable explicative sont conjointement nuls.

Pour les assureurs Vie, les résultats mettent en évidence un pouvoir
prédictif significatif des taux longs (retard 1), de l'IPC (retard 4) et
du S\&P500 (retards 2) sur les fonds propres. L'IPC (retard 4) a un
effet prédictif significatif sur le SCR et le S\&P500 (retard 3) sur le
ratio. Pour les assureurs Non-Vie, seules quelques relations prédictives
limitées apparaissent, principalement entre l'IPC (retard 3) et les
fonds propres ainsi qu'entre les taux longs (retard 1) et le ratio de
solvabilité.

\subsubsection{Estimation du modèle}\label{estimation-du-moduxe8le}

Afin d'éviter les problèmes de multicolinéarité entre indices boursiers
fortement corrélés, nous avons retenu uniquement le S\&P 500 et l'Euro
Stoxx. Ce choix permet de conserver une représentation pertinente des
dynamiques des marchés, en combinant un indice global et un indice
européen ce qui est cohérent avec l'exposition des assureurs étudiés.

\paragraph{Spécifications}\label{spuxe9cifications}

Des spécifications contemporaines ont d'abord été estimées par MCO
(cf.~Annexe Table). Malgré des diagnostics résiduels satisfaisants, les
coefficients apparaissaient majoritairement non significatifs, suggérant
l'existence de mécanismes de transmission retardés. Les modèles
dynamiques finaux ont donc été construits en deux étapes : les tests de
causalité de Granger ont d'abord permis d'identifier les retards
pertinents puis les spécifications ont été comparées via les critères
AIC et BIC afin d'assurer un équilibre entre robustesse statistique et
interprétation économique.

Les résultats mettent en évidence des mécanismes de transmission
différenciés entre branches Vie et Non-Vie ce qui est cohérent avec
leurs structures d'activité respectives.

Les écarts-types des coefficients sont corrigés à l'aide de l'estimateur
robuste de Newey-West afin de tenir compte d'une éventuelle
hétéroscédasticité et autocorrélation des résidus. Bien que les tests de
Breusch-Pagan et Ljung-Box ne rejettent pas formellement
l'homoscédasticité et l'absence d'autocorrélation, la sensibilité des
p-values à cette correction suggère la présence de déviations non
détectées par ces tests sur petit échantillon, justifiant une approche
robuste par précaution.

\subparagraph{Assureurs Vie}\label{assureurs-vie}

Fonds propres - Vie

\begin{equation}
\begin{aligned}
\Delta \ln(\text{FP}_t) = \alpha & + \rho \Delta \ln(\text{FP}_{t-1})
& + \beta_1 \Delta \text{TauxL}_{t-1}
& + \beta_2 \Delta \ln(\text{IPC})_{t-4}
& + \beta_3 \Delta \ln(\text{S\&P500})_{t-2} + \epsilon_t
\end{aligned}
\end{equation}

\begin{table}[H]
\centering\centering
\caption{\label{tab:unnamed-chunk-22}Analyse dynamique des Fonds Propres - Branche Vie}
\centering
\begin{tabular}[t]{lccc}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{3}{c}{Fonds Propres (Vie)} \\
\cmidrule(l{3pt}r{3pt}){2-4}
  & Est. & t & p\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{\num{0.0352}} & \cellcolor{gray!10}{\num{1.4257}} & \cellcolor{gray!10}{\num{0.1650}}\\
dplyr = lag(diff\_fonds\_propres, 1) & \num{-0.5197}* & \num{-2.6712} & \num{0.0124}\\
\cellcolor{gray!10}{dplyr = lag(diff\_taux\_long, 1)} & \cellcolor{gray!10}{\num{-0.0901}**} & \cellcolor{gray!10}{\num{-3.1146}} & \cellcolor{gray!10}{\num{0.0042}}\\
dplyr = lag(rendement\_sp500, 2) & \num{0.3673}** & \num{3.0802} & \num{0.0046}\\
\cellcolor{gray!10}{dplyr = lag(diff\_ipc, 4)} & \cellcolor{gray!10}{\num{-4.4542}*} & \cellcolor{gray!10}{\num{-2.5296}} & \cellcolor{gray!10}{\num{0.0173}}\\
\midrule
Num.Obs. & \num{33} &  & \\
\cellcolor{gray!10}{R2} & \cellcolor{gray!10}{\num{0.390}} & \cellcolor{gray!10}{} & \cellcolor{gray!10}{}\\
R2 Adj. & \num{0.303} &  & \\
\bottomrule
\end{tabular}
\end{table}

L'ensemble des coefficients sont significatifs au seuil de 5\% après
correction des écarts-types par la méthode de Newey-West. Les résidus ne
présentent pas d'autocorrélation selon le test de Ljung-Box, le modèle
semble donc robuste. Les résultats mettent en évidence une forte
sensibilité des fonds propres des assureurs Vie aux conditions
macro-financières. La hausse des taux d'intérêt de long terme exerce un
effet négatif sur la croissance des fonds propres traduisant
probablement la baisse de la valeur de marché des portefeuilles
obligataires lors des phases de remontée des taux. À l'inverse, les
performances des marchés actions internationaux, approximées par le S\&P
500, soutiennent positivement l'évolution des fonds propres avec un
décalage de deux trimestres confirmant l'exposition importante des
assureurs Vie aux marchés financiers. L'inflation apparaît également
comme un facteur défavorable à la solvabilité avec un effet retardé de
quatre trimestres. Ce résultat peut refléter l'augmentation progressive
des coûts de gestion et le délai d'ajustement des primes. Enfin, la
significativité du terme autorégressif souligne l'existence d'une
dynamique de persistance des fonds propres, les chocs observés tendent à
se diffuser progressivement dans le temps.

SCR - Vie

\begin{equation}
\begin{aligned}
\Delta \ln(\text{SCR}_t) = \alpha & + \rho \Delta \ln(\text{SCR}_{t-1}) 
& + \beta_1 \Delta \text{TauxL}_{t-1} 
& + \beta_2 \Delta \ln(\text{IPC})_{t-3} + \epsilon_t
\end{aligned}
\end{equation}

\begin{table}[H]
\centering\centering
\caption{\label{tab:unnamed-chunk-23}Analyse dynamique du SCR - Branche Vie}
\centering
\begin{tabular}[t]{lccc}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{3}{c}{SCR (Vie)} \\
\cmidrule(l{3pt}r{3pt}){2-4}
  & Est. & t & p\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{\num{0.0388}**} & \cellcolor{gray!10}{\num{2.9627}} & \cellcolor{gray!10}{\num{0.0058}}\\
dplyr = lag(diff\_scr, 1) & \num{-0.4102}** & \num{-2.7535} & \num{0.0098}\\
\cellcolor{gray!10}{dplyr = lag(diff\_taux\_long, 1)} & \cellcolor{gray!10}{\num{-0.0873}**} & \cellcolor{gray!10}{\num{-2.9415}} & \cellcolor{gray!10}{\num{0.0061}}\\
dplyr = lag(diff\_ipc, 3) & \num{-4.0140}** & \num{-3.3197} & \num{0.0023}\\
\midrule
\cellcolor{gray!10}{Num.Obs.} & \cellcolor{gray!10}{\num{35}} & \cellcolor{gray!10}{} & \cellcolor{gray!10}{}\\
R2 & \num{0.352} &  & \\
\cellcolor{gray!10}{R2 Adj.} & \cellcolor{gray!10}{\num{0.289}} & \cellcolor{gray!10}{} & \cellcolor{gray!10}{}\\
\bottomrule
\end{tabular}
\end{table}

Les résultats montrent que le SCR des assureurs Vie présente une
dynamique de rappel importante comme l'indique la significativité du
terme autorégressif. Les ajustements du besoin en capitals sont donc
progressifs et les chocs observés sur le SCR tendant à se résorber
partiellement au trimestre suivant. Les taux d'intérêt de long terme et
l'inflation exercent tous deux un effet négatif sur la croissance du
SCR. Ces résultats apparaissent cohérents dans la mesure où ces deux
variables influencent les mécanismes d'actualisation des engagements des
assureurs. Dans un contexte de hausse des taux, souvent associé à des
tensions inflationnistes, la valeur actuelle des passifs futurs diminue,
ce qui contribue à alléger les exigences réglementaires en capital.
L'effet retardé de l'IPC suggère toutefois que cette transmission
s'opère progressivement dans le bilan des assureurs Vie. Par ailleurs,
la constante positive et significative indique l'existence d'une
croissance résiduelle du SCR non entièrement expliquée par les variables
macro-financières intégrées au modèle.

Ratio de solvabilité - Vie

\begin{equation}
\begin{aligned}
\Delta \ln(\text{Ratio\_Moyen}_t) = \alpha & + \rho \Delta \ln(\text{Ratio\_Moyen}_{t-1})
& + \beta_1 \Delta \ln(\text{S\&P500})_{t-3} + \epsilon_t
\end{aligned}
\end{equation}

\begin{table}[H]
\centering\centering
\caption{\label{tab:unnamed-chunk-24}Analyse dynamique du ratio de solvabilité - Branche Vie}
\centering
\begin{tabular}[t]{lccc}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{3}{c}{Ratio (Vie)} \\
\cmidrule(l{3pt}r{3pt}){2-4}
  & Est. & t & p\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{\num{-0.0130}} & \cellcolor{gray!10}{\num{-1.3896}} & \cellcolor{gray!10}{\num{0.1742}}\\
dplyr = lag(diff\_ratio, 1) & \num{-0.4683}*** & \num{-4.3912} & \num{0.0001}\\
\cellcolor{gray!10}{dplyr = lag(rendement\_sp500, 3)} & \cellcolor{gray!10}{\num{0.2843}+} & \cellcolor{gray!10}{\num{1.7086}} & \cellcolor{gray!10}{\num{0.0972}}\\
\midrule
Num.Obs. & \num{35} &  & \\
\cellcolor{gray!10}{R2} & \cellcolor{gray!10}{\num{0.307}} & \cellcolor{gray!10}{} & \cellcolor{gray!10}{}\\
R2 Adj. & \num{0.263} &  & \\
\bottomrule
\end{tabular}
\end{table}

La dynamique du ratio de solvabilité semble principalement expliquée par
son propre terme retardé dont le coefficient négatif traduit un
mécanisme de retour à la moyenne dans l'ajustement de la solvabilité des
assureurs Vie. Le rendement du S\&P500 exerce un effet positif modéré
sur le ratio de solvabilité avec un retard de trois trimestres,
suggérant qu'un environnement boursier favorable améliore
progressivement la solvabilité des assureurs Vie à travers la
valorisation des actifs financiers et de meilleures conditions de
rendement des placements. L'absence d'effet significatif sur le SCR
suggère que cette amélioration des fonds propres ne semble pas être
entièrement compensée par une hausse des exigences en capital. À
l'inverse, les variables de taux d'intérêt et d'inflation n'apparaissent
plus comme des déterminants robustes des variations du ratio de
solvabilité probablement en raison d'effets compensatoires entre fonds
propres et SCR. Par ailleurs, la constante n'apparaît plus
significative, il ne semble pas y avoir de croissance structurelle du
ratio non expliquée par les variables macro-financières et la dynamique
de rappel.

\subparagraph{\texorpdfstring{Assureurs Non-Vie\\
}{Assureurs Non-Vie }}\label{assureurs-non-vie}

\hfill\break
Nous adoptons la même démarche pour les assureurs Non-Vie malgré
l'absence de résultats forts aux tests de Granger.

Fonds Propres - Non-Vie

\begin{equation}
\begin{aligned}
\Delta \ln(\text{FP}_t) = \alpha & + \rho \Delta \ln(\text{FP}_{t-1}) 
& + \beta_1 \Delta \ln(\text{IPC})_{t-3}
& + \beta_2 \Delta \text{TauxC}_{t-3}
& + \beta_3 \Delta \text{TauxL}_{t-3} + \epsilon_t
\end{aligned}
\end{equation}

\begin{table}[H]
\centering\centering
\caption{\label{tab:unnamed-chunk-25}Analyse dynamique des Fonds Propres - Branche Non-Vie}
\centering
\begin{tabular}[t]{lccc}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{3}{c}{Fonds Propres (Non-Vie)} \\
\cmidrule(l{3pt}r{3pt}){2-4}
  & Est. & t & p\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{\num{0.0367}**} & \cellcolor{gray!10}{\num{3.5278}} & \cellcolor{gray!10}{\num{0.0014}}\\
dplyr = lag(diff\_fonds\_propres, 1) & \num{-0.4123}*** & \num{-4.9547} & \num{<1e-04}\\
\cellcolor{gray!10}{dplyr = lag(diff\_ipc, 3)} & \cellcolor{gray!10}{\num{-4.1880}*} & \cellcolor{gray!10}{\num{-2.3698}} & \cellcolor{gray!10}{\num{0.0244}}\\
dplyr = lag(diff\_taux\_court, 3) & \num{-0.0332} & \num{-1.4900} & \num{0.1467}\\
\cellcolor{gray!10}{dplyr = lag(diff\_taux\_long, 3)} & \cellcolor{gray!10}{\num{0.0762}*} & \cellcolor{gray!10}{\num{2.1063}} & \cellcolor{gray!10}{\num{0.0436}}\\
\midrule
Num.Obs. & \num{35} &  & \\
\cellcolor{gray!10}{R2} & \cellcolor{gray!10}{\num{0.366}} & \cellcolor{gray!10}{} & \cellcolor{gray!10}{}\\
R2 Adj. & \num{0.281} &  & \\
\bottomrule
\end{tabular}
\end{table}

Les assureurs non-vie semblent davantage déconnectés des taux et des
marchés financiers que les assureurs Vie. La dynamique de leurs fonds
propres parait essentiellement dictée par sa propre inertie. Cependant,
la constante est significative indiquant une croissance structurelle
indépendante des fluctuations macro-financières. Cette dynamique suggère
que la richesse nette de cette branche repose principalement sur le
cycle d'exploitation (primes et sinistres) plutôt que sur le cycle
financier.

SCR - Non-Vie

\begin{equation}
\begin{aligned}
\Delta \ln(\text{SCR}_t) = \alpha & + \rho \Delta \ln(\text{SCR}_{t-1})
& + \beta_1 \Delta \text{TauxC}_{t-3} + \epsilon_t
\end{aligned}
\end{equation}

\begin{table}[H]
\centering\centering
\caption{\label{tab:unnamed-chunk-26}Analyse dynamique du SCR - Branche Non-Vie}
\centering
\begin{tabular}[t]{lccc}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{3}{c}{SCR (Non-Vie)} \\
\cmidrule(l{3pt}r{3pt}){2-4}
  & Est. & t & p\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{\num{0.0177}*} & \cellcolor{gray!10}{\num{2.2132}} & \cellcolor{gray!10}{\num{0.0341}}\\
dplyr = lag(diff\_scr, 1) & \num{-0.3273}*** & \num{-4.2606} & \num{0.0002}\\
\cellcolor{gray!10}{dplyr = lag(diff\_taux\_court, 3)} & \cellcolor{gray!10}{\num{-0.0233}**} & \cellcolor{gray!10}{\num{-3.0898}} & \cellcolor{gray!10}{\num{0.0041}}\\
\midrule
Num.Obs. & \num{35} &  & \\
\cellcolor{gray!10}{R2} & \cellcolor{gray!10}{\num{0.154}} & \cellcolor{gray!10}{} & \cellcolor{gray!10}{}\\
R2 Adj. & \num{0.101} &  & \\
\bottomrule
\end{tabular}
\end{table}

Les résultats montrent également qu'une hausse des taux d'intérêt de
court terme réduit la croissance du SCR avec un retard de trois
trimestres. Ce résultat suggère une transmission différée des conditions
de taux aux exigences réglementaires en capital, possiblement via les
mécanismes d'actualisation des engagements et l'évolution de
l'exposition au risque de taux. La constante positive suggère une
dynamique de croissance structurelle interne peu sensible aux chocs
macro-financiers immédiats.

Ratio de solvabilité - Non-Vie

\begin{equation}
\begin{aligned}
\Delta \ln(\text{Ratio\_Moyen}_t) = \alpha & + \rho \Delta \ln(\text{Ratio\_Moyen}_{t-1})
& + \beta_1 \Delta \text{TauxL}_{t-3} & + \beta_2 \Delta \text{TauxC}_{t-3} + \epsilon_t
\end{aligned}
\end{equation}

\begin{table}[H]
\centering\centering
\caption{\label{tab:unnamed-chunk-27}Analyse dynamique du ratio de solvabilité - Branche Non-Vie}
\centering
\begin{tabular}[t]{lccc}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{3}{c}{Ratio (Non-Vie)} \\
\cmidrule(l{3pt}r{3pt}){2-4}
  & Est. & t & p\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{\num{-0.0046}+} & \cellcolor{gray!10}{\num{-1.7371}} & \cellcolor{gray!10}{\num{0.0923}}\\
dplyr = lag(diff\_ratio, 1) & \num{-0.3611}*** & \num{-8.8205} & \num{<1e-04}\\
\cellcolor{gray!10}{dplyr = lag(diff\_taux\_court, 3)} & \cellcolor{gray!10}{\num{-0.0273}***} & \cellcolor{gray!10}{\num{-6.4019}} & \cellcolor{gray!10}{\num{<1e-04}}\\
dplyr = lag(diff\_taux\_long, 3) & \num{0.0407}** & \num{3.1076} & \num{0.0040}\\
\midrule
\cellcolor{gray!10}{Num.Obs.} & \cellcolor{gray!10}{\num{35}} & \cellcolor{gray!10}{} & \cellcolor{gray!10}{}\\
R2 & \num{0.253} &  & \\
\cellcolor{gray!10}{R2 Adj.} & \cellcolor{gray!10}{\num{0.180}} & \cellcolor{gray!10}{} & \cellcolor{gray!10}{}\\
\bottomrule
\end{tabular}
\end{table}

Une hausse des taux d'intérêt de long terme améliore le ratio de
solvabilité avec un retard de trois trimestres, probablement via
l'augmentation des fonds propres et l'amélioration des revenus
financiers. À l'inverse, les taux courts exercent un effet négatif sur
le ratio de solvabilité. Ce résultat suggère qu'un relèvement des taux
courts peut temporairement détériorer l'équilibre prudentiel des
assureurs Non-Vie.

\paragraph{Diagnostics et limites du
modèle}\label{diagnostics-et-limites-du-moduxe8le}

Ces résultats doivent être interprétés avec prudence en raison de
plusieurs limites économétriques. La taille réduite de l'échantillon
restreint la puissance statistique des estimations. L'ensemble des
modèles estimés satisfont les conditions de validité économétrique : les
tests de Jarque-Bera, Breusch-Pagan et Ljung-Box ne rejettent pas la
normalité des résidus, l'homoscédasticité et l'absence d'autocorrélation
(cf.~Annexe Tables). Néanmoins, compte tenu de la faible puissance de
ces tests sur petit échantillon et de la sensibilité des p-values à la
correction, l'estimateur de Newey-West a été appliqué à l'ensemble des
modèles afin de garantir la robustesse des inférences. Par ailleurs, un
biais d'endogénéité lié à l'omission de variables pertinentes ne peut
être exclu. Les variables macro-financières retenues sont susceptibles
d'être corrélées avec d'autres déterminants de la solvabilité non
intégrés au modèle ce qui limite la validité de cette modélisation.

Par ailleurs, cette approche en différences ne permet pas d'identifier
les relations d'équilibre de long terme. Ces éléments justifient le
recours à une spécification ARDL qui permet d'intégrer simultanément
dynamiques de court terme et relations de cointégration éventuelles.

\subsection{Modèle ARDL}\label{moduxe8le-ardl}

Le modèle ARDL (Autoregressive Distributed Lag) est une approche
économétrique puissante pour examiner les liens dynamiques entre des
variables dans le temps. Contrairement aux méthodes classiques de
cointégration, l'ARDL est particulièrement flexible car il permet
d'analyser des séries ayant différents ordres d'intégration (\(I(0)\) ou
\(I(1)\))

\subsubsection{Formulation Mathématique du
Modèle}\label{formulation-mathuxe9matique-du-moduxe8le}

Le modèle fusionne une partie autorégressive (les valeurs passées du
ratio) et des délais répartis (les valeurs actuelles et passées des
marchés).L'équation structurelle est la suivante:

\[ratio_{t} = \phi + \sum_{i=1}^{p} a_{i} ratio_{t-i} + \sum_{j=0}^{q} b_{j} X_{t-j} + \epsilon_{t}\]

Où :

\begin{itemize}
\tightlist
\item
  \(ratio_{t}\) : La variable dépendante.
\item
  \(X_{t}\) : Les variables explicatives.
\item
  \(p, q\) : Les ordres de retard respectifs.
\item
  \(\epsilon_{t}\) : Le terme d'erreur (bruit blanc)
\end{itemize}

Pour estimer notre modèle nous procedons en 3 étapes :

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Variables explicatives et Stationnarité.
\item
  Recherche des retard optimaux et estimation du modèle
\item
  Diagnostic du modèle
\end{enumerate}

\subsubsection{Variables explicatives et
Stationnarité}\label{variables-explicatives-et-stationnarituxe9}

Pour ce modèle, les variables explicatives retenues se divisent en deux
catégories :

\begin{itemize}
\tightlist
\item
  Les variables de marché : les indices boursiers S\&P 500 et CAC 40.
\item
  Les variables macroéconomiques : le taux de croissance du PIB,
  l'Indice des Prix à la Consommation (IPC) et le taux d'intérêt de long
  terme.
\end{itemize}

Afin de traiter les séries présentant une croissance de nature
exponentielle, nous avons appliqué une transformation logarithmique aux
indices boursiers (CAC 40, S\&P 500) ainsi qu'à l'IPC. Cette pratique,
standard en économétrie financière, répond à un objectif analytique
majeur : elle permet de linéariser ces séries et de convertir les
variations absolues en variations relatives. Ainsi, les coefficients
estimés du modèle s'interpréteront directement comme des élasticités,
mesurant l'impact d'une variation de \(1 \%\) d'un indice de marché ou
des prix sur le ratio de solvabilité.

Comme souligné précédemment, la validité du test de cointégration aux
bornes de l'approche ARDL repose sur l'hypothèse stricte qu'aucune série
n'est intégrée d'ordre 2, soit \(I(2)\), ou supérieur, ce qui rendrait
la méthode caduque. L'évaluation de l'ordre d'intégration de chaque
variable a donc été menée rigoureusement en suivant la procédure
séquentielle du test de Dickey-Fuller Augmenté (ADF) et du test de KPSS,
avec une méthodologie identique à celle détaillée dans la section
précédente.

À l'issue de ces tests de racine unitaire, les résultats suivants se
dégagent :

\begin{itemize}
\tightlist
\item
  Variables \(I(0)\) : Le ratio de solvabilité et le taux de croissance
  du PIB sont stationnaires en niveau.
\item
  Variables \(I(1)\) : Les logarithmes des variables de marché (CAC 40,
  S\&P 500) et de l'inflation (IPC) présentent une racine unitaire en
  niveau, mais deviennent stationnaires après un passage en différence
  première.
\item
  Traitement de la variable \(I(2)\) : Le test a révélé que le taux
  d'intérêt de long terme est intégré d'ordre 2. Pour l'introduire de
  manière valide dans le modèle sans violer les hypothèses de l'ARDL,
  cette série a été préalablement différenciée une fois. La série
  résultante (la variation du taux d'intérêt) est alors \(I(1)\).
\end{itemize}

Cette coexistence de variables explicatives intégrées d'ordres mixtes,
\(I(0)\) et \(I(1)\), justifie pleinement le recours et la pertinence de
la modélisation ARDL pour notre étude.

\subsubsection{Recherche des retard optimaux et estimation du
modèle}\label{recherche-des-retard-optimaux-et-estimation-du-moduxe8le}

\paragraph{Retards optimaux}\label{retards-optimaux}

\begin{longtable}[t]{rrrrrr}
\caption{\label{tab:estimation_modele}Retards optimaux sélectionnés}\\
\toprule
ratio & l\_ipc & taux\_pib & d\_taux\_l & l\_sp & l\_cac\\
\midrule
2 & 3 & 0 & 1 & 0 & 0\\
\bottomrule
\end{longtable}

Afin d'optimiser la précision de l'estimation, le nombre idéal de
retards a été fixé automatiquement en s'appuyant sur des critères
d'information. Notre choix s'est spécifiquement porté sur le critère de
Schwarz, ou critère d'information bayésien (BIC). Contrairement au
critère d'Akaike (AIC), le BIC pénalise plus fortement la complexité du
modèle (le nombre de paramètres estimés), ce qui permet de privilégier
une spécification plus stricte et parcimonieuse, limitant ainsi le
risque de surapprentissage.

L'algorithme d'optimisation a convergé vers la structure optimale
suivante : un modèle \(\text{ARDL}(2, 3, 0, 1, 0, 0)\). L'équation
correspondante peut se formaliser ainsi :

\[\begin{aligned}
\text{ratio}_t = \alpha_0 & + \gamma_1 \text{ratio}_{t-1} + \gamma_2 \text{ratio}_{t-2} \\
& + \beta_{1,0} l\_ipc_t + \beta_{1,1} l\_ipc_{t-1} + \beta_{1,2} l\_ipc_{t-2} + \beta_{1,3} l\_ipc_{t-3} \\
& + \beta_{2,0} \text{taux\_pib}_t + \beta_{3,0} d\_taux\_l_t + \beta_{3,1} d\_taux\_l_{t-1} \\
& + \beta_{4,0} l\_sp_t + \beta_{5,0} l\_cac_t + \epsilon_t
\end{aligned}\]

\paragraph{Test des bornes
(cointégration)}\label{test-des-bornes-cointuxe9gration}

\begin{verbatim}

    Bounds F-test (Wald) for no cointegration

data:  d(ratio) ~ L(ratio, 1) + L(l_ipc, 1) + taux_pib + L(d_taux_l,     1) + l_sp + l_cac + d(L(ratio, 1)) + d(l_ipc) + d(L(l_ipc,     1)) + d(L(l_ipc, 2)) + d(d_taux_l)
F = 8.0944, p-value = 1e-06
alternative hypothesis: Possible cointegration
null values:
   k    T 
   5 1000 
\end{verbatim}

\textbf{Interprétation des résultats : Cointégration}

La première étape de l'analyse consiste à vérifier l'existence d'une
relation d'équilibre de long terme entre le ratio de solvabilité et ses
déterminants via le test aux bornes (Bounds F-test). La statistique de
Fisher obtenue est de 8.09 avec une p-value de 0. Ce résultat, largement
inférieur au seuil de \(5 \%\), nous permet de rejeter l'hypothèse nulle
d'absence de cointégration. Il existe donc une relation stable et non
fallacieuse entre ces variables sur le long terme, ce qui valide
l'utilisation du modèle ARDL pour analyser la dynamique du ratio.

\paragraph{Coefficients de long terme}\label{coefficients-de-long-terme}

\begin{verbatim}
         Term    Estimate Std. Error   t value     Pr(>|t|)
1 (Intercept)  4.17083425 1.14619512  3.638852 0.0016339399
2       l_ipc -0.49536062 0.38120351 -1.299465 0.2085644204
3    taux_pib -0.41451004 0.28801957 -1.439173 0.1655694822
4    d_taux_l  0.07817369 0.04483171  1.743714 0.0965614870
5        l_sp  0.45504111 0.11565555  3.934451 0.0008200249
6       l_cac -0.38493608 0.17086842 -2.252822 0.0356567527
\end{verbatim}

\textbf{Interprétation des résultats : Relation de Long Terme}

log(S\&P 500) et log(CAC 40) ont des coefficients significatif au seuil
de \(5\%\). La variation du taux long terme est marginalement
significatif au seuil de 10\% (\(t = 1.74\), \(p = 0.097\)). On peut
donc dire qu'une appréciation de 1\% de l'indice américain est associée
à une hausse de 0.46 point du ratio de solvabilité à long terme.

log(IPC) et Taux PIB sont non significativent. Cela indiquent que ces
variables macroéconomiques n'exercent pas d'influence statistiquement
détectable sur le ratio de solvabilité à long terme, une fois les effets
de marché contrôlés.

Le ratio de solvabilité des sociétés d'assurances est structurellement
lié aux dynamiques des marchés actions. La diversification géographique
apparaît comme un facteur clé : l'exposition au marché américain
renforce la solvabilité, tandis qu'une concentration sur le marché
européen constitue un facteur de vulnérabilité. Ce résultat plaide pour
une gestion prudentielle attentive à la composition géographique des
portefeuilles.

\paragraph{Dynamique de court terme}\label{dynamique-de-court-terme}

Pour estimer la dynamique de court terme, on réecrit le modèle sous la
forme de correction d'erreur. L'estimation du modèle sous sa forme non
contrainte à correction d'erreur permet d'analyser la vitesse à laquelle
le ratio de solvabilité s'ajuste après un choc exogène. Il s'agit d'un
transformation algébrique de l'équation de base du modèle :

\[\begin{aligned}
\Delta \text{ratio}_t = \alpha_0 &+ \underbrace{\lambda \cdot \left[ \text{ratio}_{t-1} - \left( \beta_1 l\_ipc_{t-1} + \beta_2 \text{taux\_pib}_{t-1} + \beta_3 d\_taux\_l_{t-1} + \beta_4 l\_sp_{t-1} + \beta_5 l\_cac_{t-1} \right) \right]}_{\textbf{Force de Rappel (ECT}_{t-1}\textbf{)}} \\
&+ \gamma_{1} \Delta \text{ratio}_{t-1} \\
&+ \delta_{1,0} \Delta l\_ipc_t + \delta_{1,1} \Delta l\_ipc_{t-1} + \delta_{1,2} \Delta l\_ipc_{t-2} \\
&+ \delta_{3,0} \Delta d\_taux\_l_t + \epsilon_t
\end{aligned}\]

\(\lambda\) est le coefficient d'ajustement : correspond au coefficient
du Terme de Correction d'Erreur (ECT). Dans un modèle de cointégration,
elle mesure la capacité de la variable dépendante (le ratio de
solvabilité) à retourner vers son équilibre de long terme après un choc
macroéconomique.D'un point de vue mathématique, elle indique quelle
proportion de l'écart à l'équilibre constaté à la période \(t-1\) est
résorbée à la période \(t\).

Ce coefficient est estimé à \(\lambda = −1.44 \;(p < 0.001)\), étant
significatif au seuil de 1\%. La négativité du coefficient confirme
l'existence d'une relation de cointégration entre le ratio de
solvabilité et les variables macroéconomiques.La valeur absolue
supérieure à l'unité traduit une dynamique de convergence oscillatoire :
le système sur-corrige les écarts à l'équilibre d'un trimestre à
l'autre. Ce résultat est cohérent avec la forte volatilité observée sur
le graphique du ratio, notamment lors de la période 2019-2022, où les
mesures de sauvegarde et la reprise des marchés ont provoqué des
ajustements brutaux et rapides de la solvabilité globale du marché.

\begin{flushleft}\includegraphics{Stat_desc_files/figure-latex/unnamed-chunk-31-1} \end{flushleft}

\paragraph{Diagnostic et limites du
modèle}\label{diagnostic-et-limites-du-moduxe8le}

\begin{enumerate}
\def\labelenumi{(\roman{enumi})}
\tightlist
\item
  Diagnostic des résidus
\end{enumerate}

La validité des inférences statistiques repose sur le respect des
hypothèses fondamentales du modèle de régression. Trois batteries de
tests ont été conduites pour vérifier la qualité des résidus.

Test d'autocorrélation (Breusch-Godfrey) : la statistique LM = 9.47
associée à une p-value de 0.050 ne permet pas de rejeter l'hypothèse
nulle d'absence d'autocorrélation au seuil de 5\%. La structure de
retards retenue capture donc correctement la dynamique temporelle des
données, garantissant la validité des écarts-types estimés.

Test de normalité (Jarque-Bera) : la statistique χ² = 2.04 (p-value =
0.36) conduit au non-rejet de l'hypothèse de normalité des résidus. Ce
résultat assure la validité des tests de Student et de Fisher, même sur
un échantillon de taille modeste.

Tests de stabilité structurelle (CUSUM et CUSUM²) : les sommes cumulées
des résidus récursifs demeurent à l'intérieur des bandes de confiance à
5\% sur l'ensemble de la période d'estimation. Les coefficients du
modèle sont donc stables dans le temps, confirmant l'absence de rupture
structurelle.

\begin{enumerate}
\def\labelenumi{(\roman{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Limites du modèles
\end{enumerate}

Malgré la robustesse des diagnostics, plusieurs limites méthodologiques
doivent être soulignées.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Contrainte d'échantillon : avec seulement 35 observations
  trimestrielles, le modèle souffre d'une faible puissance statistique.
  Cette taille limite le nombre de variables explicatives et de retards
  pouvant être introduits sans surparamétrage
\item
  Agrégation sectorielle : l'utilisation d'un ratio de solvabilité moyen
  masque l'hétérogénéité des institutions. Les dynamiques d'ajustement
  peuvent différer significativement entre assureurs, banques et autres
  acteurs financiers.
\item
  Période d'estimation atypique : l'échantillon inclut des épisodes de
  stress majeurs (crise Covid-19, choc inflationniste 2022-2023) qui
  peuvent influencer de manière disproportionnée les coefficients
  estimés. La généralisation des résultats à des périodes plus stables
  requiert une certaine prudence.
\end{enumerate}

\section{Conclusion}\label{conclusion}

Cette étude démontre que la solvabilité des assureurs n'est pas une
donnée statique, mais le produit de dynamiques complexes et
différenciées selon les segments de marché. Nos résultats soulignent une
hétérogénéité marquée dans la spécificité des métiers : tandis que les
assureurs Vie voient leur solidité financière portée par la performance
des marchés actions, notamment le S\&P 500, les assureurs Non-Vie
affichent une vulnérabilité plus prononcée aux fluctuations des taux
d'intérêt. Cette sensibilité sectorielle s'inscrit par ailleurs dans une
dynamique de marchés globaux où la diversification géographique joue un
rôle protecteur prépondérant. L'analyse ARDL met ainsi en lumière qu'une
diversification du portefeuille via l'exposition au marché d'action
américain renforce la solvabilité, là où une concentration sur le marché
européen peut constituer un facteur de fragilité. Enfin, bien que la
mise en évidence d'une relation de cointégration confirme une stabilité
sous tension avec une convergence de long terme, la trajectoire du ratio
reste marquée par des oscillations trimestrielles dues à une
sur-correction des chocs macroéconomiques sur la période etudié. Si ces
mécanismes de rappel interne assurent une certaine résilience au
secteur, la dépendance aux variables financières demeure majeure. Ces
conclusions plaident donc en faveur d'une gestion proactive de
l'allocation d'actifs et d'une surveillance accrue des cycles de taux,
garantissant que la promesse d'indemnisation initiale soit honorée en
dépit de la volatilité des marchés.

\section{Annexes}\label{annexes}

\subsection{Analyse descriptive}\label{analyse-descriptive}

\begin{flushleft}\includegraphics{Stat_desc_files/figure-latex/unnamed-chunk-32-1} \end{flushleft}

\begin{flushleft}\includegraphics{Stat_desc_files/figure-latex/unnamed-chunk-34-1} \end{flushleft}

\subsubsection{Les indices boursiers.}\label{les-indices-boursiers.}

Les indices boursiers reflètent la performance globale des actions. Une
baisse de ces indices entraîne une diminution de la valeur des actifs en
actions détenus par les assureurs, ce qui se traduit par une
augmentation du SCR actions et une réduction du ratio de solvabilité.
Dans cette étude, deux indices boursiers sont considérés: l'EURO STOXX
et le CAC 40.

\paragraph{L'EURO STOXX 50}\label{leuro-stoxx-50}

L'\emph{EURO STOXX 50} est un indice boursier regroupant les 50
principales sociétés cotées de la zone euro, sélectionnées
principalement en fonction de leur capitalisation boursière flottante.
Il constitue un indicateur de la santé économique et des performances
des marchés financiers au sein de la zone euro. Le graphique présenté
ci-dessous illustre l'évolution des valeurs maximales et minimales de
cet indice deouis \(2015\) jusqu'en \(2025\).

\begin{flushleft}\includegraphics{Stat_desc_files/figure-latex/unnamed-chunk-38-1} \end{flushleft}

Ces indices évoluent de manière globalement parallèle, suivant une
tendance générale à la hausse. Néanmoins, une chute marquée est observée
en mars 2020, atteignant un niveau minimal, en raison des mesures de
restriction et de l'incertitude économique engendrées par la pandémie de
COVID-19. C'est en effet en cette période que Donald Trump avait annoncé
la restriction des entrées sur le téritoire américain; source d'une
panique boursière.

\paragraph{Le Standard \& Poor's 500 (S\&P
500)}\label{le-standard-poors-500-sp-500}

Le S\&P 500 est un indice boursier large représentant les 500 plus
grandes sociétés cotées aux États-Unis, pondérées en fonction de leur
capitalisation boursière flottante. Il est largement utilisé comme
référence du marché actions américain et constitue un indicateur clé de
la performance économique et financière du pays. L'évolution des valeurs
maximales et minimales de cet indice entre 2015 et 2025, présentée dans
le graphique ci-dessous, permet d'analyser la volatilité du marché ainsi
que l'impact des événements macroéconomiques et géopolitiques sur les
marchés financiers américains

\begin{flushleft}\includegraphics{Stat_desc_files/figure-latex/unnamed-chunk-39-1} \end{flushleft}

Le S\&P 500 connaît une tendence croissance sur toute la période avec
également une pertubation en mars 2020 due à la pandémie de OVID-19.
Toutefois cette indice est visiblement moins volatile que l'EURO STOXX
50.

\paragraph{L'indice CAC 40}\label{lindice-cac-40}

L'indice \emph{CAC 40} constitue le principal indice boursier de la
Bourse de Paris, reflétant la performance des 40 actions les plus
importantes et les plus activement négociées sur Euronext Paris. Le
graphique ci-après illustre l'évolution de ses valeurs maximales et
minimales au fil du temps.

\begin{flushleft}\includegraphics{Stat_desc_files/figure-latex/unnamed-chunk-42-1} \end{flushleft}

Comme pour l'EURO STOXX, les valeurs de l'indice CAC 40 évoluent de
manière parallèle et croissante avec également une chutte marqué en mars
2020 pour la même raison que précédemment.

\paragraph{L'indice DAX}\label{lindice-dax}

Le DAX (Deutscher Aktienindex) est l'indice de référence du marché
boursier allemand, regroupant les 40 principales sociétés cotées à la
Bourse de Francfort, sélectionnées principalement en fonction de leur
capitalisation boursière flottante. C'est l'équivalent allemend du CAC
40. Le graphique ci-après représente les variation de cet indice sur la
période \(2015-2025.\)

\begin{flushleft}\includegraphics{Stat_desc_files/figure-latex/unnamed-chunk-43-1} \end{flushleft}

\subsection{Modélisation}\label{moduxe9lisation-1}

\subsubsection{Régression en
différence}\label{ruxe9gression-en-diffuxe9rence}

\begin{table}[H]
\centering\centering
\caption{\label{tab:unnamed-chunk-44}Résultats de la régression du ratio de solvabilité - Vie}
\centering
\begin{tabular}[t]{lcccc}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{4}{c}{(1)} \\
\cmidrule(l{3pt}r{3pt}){2-5}
  & Est. & S.E. & t & p\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{\num{-0.0158}} & \cellcolor{gray!10}{\num{0.0205}} & \cellcolor{gray!10}{\num{-0.7704}} & \cellcolor{gray!10}{\num{0.4475}}\\
rendement\_stoxx & \num{0.1268} & \num{0.2570} & \num{0.4936} & \num{0.6255}\\
\cellcolor{gray!10}{rendement\_sp500} & \cellcolor{gray!10}{\num{0.2066}} & \cellcolor{gray!10}{\num{0.2412}} & \cellcolor{gray!10}{\num{0.8566}} & \cellcolor{gray!10}{\num{0.3989}}\\
diff\_ipc & \num{0.6865} & \num{2.6065} & \num{0.2634} & \num{0.7942}\\
\cellcolor{gray!10}{diff\_taux\_court} & \cellcolor{gray!10}{\num{-0.0432}} & \cellcolor{gray!10}{\num{0.0382}} & \cellcolor{gray!10}{\num{-1.1325}} & \cellcolor{gray!10}{\num{0.2670}}\\
diff\_taux\_long & \num{0.0599} & \num{0.0455} & \num{1.3172} & \num{0.1984}\\
\cellcolor{gray!10}{diff\_pib} & \cellcolor{gray!10}{\num{0.2577}} & \cellcolor{gray!10}{\num{0.4199}} & \cellcolor{gray!10}{\num{0.6138}} & \cellcolor{gray!10}{\num{0.5443}}\\
\midrule
Num.Obs. & \num{35} &  &  & \\
\cellcolor{gray!10}{R2} & \cellcolor{gray!10}{\num{0.176}} & \cellcolor{gray!10}{} & \cellcolor{gray!10}{} & \cellcolor{gray!10}{}\\
R2 Adj. & \num{-0.000} &  &  & \\
\bottomrule
\end{tabular}
\end{table}

\begin{longtable}[t]{llrrl}
\caption{\label{tab:unnamed-chunk-45}Tests sur les résidus modèle ratio - Vie}\\
\toprule
 & Test & Statistique & P\_value & Verdict\\
\midrule
\cellcolor{gray!10}{DW} & \cellcolor{gray!10}{Autocorrélation (Durbin-Watson)} & \cellcolor{gray!10}{2.6972} & \cellcolor{gray!10}{0.9789} & \cellcolor{gray!10}{Hypothèse validée}\\
X-squared & Indépendance Globale (Ljung-Box) & 17.6091 & 0.0619 & Bruit blanc confirmé\\
\cellcolor{gray!10}{BP} & \cellcolor{gray!10}{Homoscédasticité (Breusch-Pagan)} & \cellcolor{gray!10}{4.5900} & \cellcolor{gray!10}{0.5974} & \cellcolor{gray!10}{Hypothèse validée}\\
W & Normalité (Shapiro-Wilk) & 0.9649 & 0.3184 & Hypothèse validée\\
\bottomrule
\end{longtable}

\begin{longtable}[t]{lrrl}
\caption{\label{tab:unnamed-chunk-46}Tests diagnostiques - Fonds Propres Vie}\\
\toprule
Test & Statistique & p.value & Hypothèse\_nulle\\
\midrule
\cellcolor{gray!10}{Ljung-Box} & \cellcolor{gray!10}{0.0971} & \cellcolor{gray!10}{0.7554} & \cellcolor{gray!10}{Pas d'autocorrélation}\\
Jarque-Bera & 0.1760 & 0.9158 & Normalité des résidus\\
\cellcolor{gray!10}{Breusch-Pagan} & \cellcolor{gray!10}{1.7255} & \cellcolor{gray!10}{0.7861} & \cellcolor{gray!10}{Homoscédasticité}\\
\bottomrule
\end{longtable}

\begin{longtable}[t]{llr}
\caption{\label{tab:unnamed-chunk-46}Facteurs d'inflation de la variance (VIF) - Fonds Propres Vie}\\
\toprule
 & Variable & VIF\\
\midrule
\cellcolor{gray!10}{dplyr::lag(diff\_fonds\_propres, 1)} & \cellcolor{gray!10}{dplyr::lag(diff\_fonds\_propres, 1)} & \cellcolor{gray!10}{1.309}\\
dplyr::lag(diff\_taux\_long, 1) & dplyr::lag(diff\_taux\_long, 1) & 1.051\\
\cellcolor{gray!10}{dplyr::lag(rendement\_sp500, 2)} & \cellcolor{gray!10}{dplyr::lag(rendement\_sp500, 2)} & \cellcolor{gray!10}{1.068}\\
dplyr::lag(diff\_ipc, 4) & dplyr::lag(diff\_ipc, 4) & 1.281\\
\bottomrule
\end{longtable}

\begin{longtable}[t]{lrrl}
\caption{\label{tab:unnamed-chunk-47}Tests diagnostiques - SCR Vie}\\
\toprule
Test & Statistique & p.value & Hypothèse\_nulle\\
\midrule
\cellcolor{gray!10}{Ljung-Box} & \cellcolor{gray!10}{0.0971} & \cellcolor{gray!10}{0.7554} & \cellcolor{gray!10}{Pas d'autocorrélation}\\
Jarque-Bera & 0.1760 & 0.9158 & Normalité des résidus\\
\cellcolor{gray!10}{Breusch-Pagan} & \cellcolor{gray!10}{1.7255} & \cellcolor{gray!10}{0.7861} & \cellcolor{gray!10}{Homoscédasticité}\\
\bottomrule
\end{longtable}

\begin{longtable}[t]{llr}
\caption{\label{tab:unnamed-chunk-47}Facteurs d'inflation de la variance (VIF) - SCR Vie}\\
\toprule
 & Variable & VIF\\
\midrule
\cellcolor{gray!10}{dplyr::lag(diff\_scr, 1)} & \cellcolor{gray!10}{dplyr::lag(diff\_scr, 1)} & \cellcolor{gray!10}{1.054}\\
dplyr::lag(diff\_taux\_long, 1) & dplyr::lag(diff\_taux\_long, 1) & 1.212\\
\cellcolor{gray!10}{dplyr::lag(diff\_ipc, 3)} & \cellcolor{gray!10}{dplyr::lag(diff\_ipc, 3)} & \cellcolor{gray!10}{1.243}\\
\bottomrule
\end{longtable}

\begin{longtable}[t]{lrrl}
\caption{\label{tab:unnamed-chunk-48}Tests diagnostiques - Ratio de solvabilité Vie}\\
\toprule
Test & Statistique & p.value & Hypothèse\_nulle\\
\midrule
\cellcolor{gray!10}{Ljung-Box} & \cellcolor{gray!10}{0.6204} & \cellcolor{gray!10}{0.4309} & \cellcolor{gray!10}{Pas d'autocorrélation}\\
Jarque-Bera & 4.2546 & 0.1192 & Normalité des résidus\\
\cellcolor{gray!10}{Breusch-Pagan} & \cellcolor{gray!10}{3.5422} & \cellcolor{gray!10}{0.1701} & \cellcolor{gray!10}{Homoscédasticité}\\
\bottomrule
\end{longtable}

\begin{longtable}[t]{llr}
\caption{\label{tab:unnamed-chunk-48}Facteurs d'inflation de la variance (VIF) - Ratio Vie}\\
\toprule
 & Variable & VIF\\
\midrule
\cellcolor{gray!10}{dplyr::lag(diff\_ratio, 1)} & \cellcolor{gray!10}{dplyr::lag(diff\_ratio, 1)} & \cellcolor{gray!10}{1}\\
dplyr::lag(rendement\_sp500, 3) & dplyr::lag(rendement\_sp500, 3) & 1\\
\bottomrule
\end{longtable}

\begin{longtable}[t]{lrrl}
\caption{\label{tab:unnamed-chunk-49}Tests diagnostiques - Fonds propres Non-Vie}\\
\toprule
Test & Statistique & p.value & Hypothèse\_nulle\\
\midrule
\cellcolor{gray!10}{Ljung-Box} & \cellcolor{gray!10}{0.3490} & \cellcolor{gray!10}{0.5547} & \cellcolor{gray!10}{Pas d'autocorrélation}\\
Jarque-Bera & 3.7717 & 0.1517 & Normalité des résidus\\
\cellcolor{gray!10}{Breusch-Pagan} & \cellcolor{gray!10}{1.3123} & \cellcolor{gray!10}{0.8593} & \cellcolor{gray!10}{Homoscédasticité}\\
\bottomrule
\end{longtable}

\begin{longtable}[t]{llr}
\caption{\label{tab:unnamed-chunk-49}Facteurs d'inflation de la variance (VIF) - Fond propres Non-Vie}\\
\toprule
 & Variable & VIF\\
\midrule
\cellcolor{gray!10}{dplyr::lag(diff\_fonds\_propres, 1)} & \cellcolor{gray!10}{dplyr::lag(diff\_fonds\_propres, 1)} & \cellcolor{gray!10}{1.055}\\
dplyr::lag(diff\_ipc, 3) & dplyr::lag(diff\_ipc, 3) & 1.465\\
\cellcolor{gray!10}{dplyr::lag(diff\_taux\_court, 3)} & \cellcolor{gray!10}{dplyr::lag(diff\_taux\_court, 3)} & \cellcolor{gray!10}{1.622}\\
dplyr::lag(diff\_taux\_long, 3) & dplyr::lag(diff\_taux\_long, 3) & 1.325\\
\bottomrule
\end{longtable}

\begin{longtable}[t]{lrrl}
\caption{\label{tab:unnamed-chunk-50}Tests diagnostiques - Fonds propres Non-Vie}\\
\toprule
Test & Statistique & p.value & Hypothèse\_nulle\\
\midrule
\cellcolor{gray!10}{Ljung-Box} & \cellcolor{gray!10}{0.0381} & \cellcolor{gray!10}{0.8452} & \cellcolor{gray!10}{Pas d'autocorrélation}\\
Jarque-Bera & 18.0553 & 0.0001 & Normalité des résidus\\
\cellcolor{gray!10}{Breusch-Pagan} & \cellcolor{gray!10}{0.2348} & \cellcolor{gray!10}{0.8892} & \cellcolor{gray!10}{Homoscédasticité}\\
\bottomrule
\end{longtable}

\begin{longtable}[t]{llr}
\caption{\label{tab:unnamed-chunk-50}Facteurs d'inflation de la variance (VIF) - Fond propres Non-Vie}\\
\toprule
 & Variable & VIF\\
\midrule
\cellcolor{gray!10}{dplyr::lag(diff\_scr, 1)} & \cellcolor{gray!10}{dplyr::lag(diff\_scr, 1)} & \cellcolor{gray!10}{1.012}\\
dplyr::lag(diff\_taux\_court, 3) & dplyr::lag(diff\_taux\_court, 3) & 1.012\\
\bottomrule
\end{longtable}

\begin{longtable}[t]{lrrl}
\caption{\label{tab:unnamed-chunk-51}Tests diagnostiques - Fonds propres Non-Vie}\\
\toprule
Test & Statistique & p.value & Hypothèse\_nulle\\
\midrule
\cellcolor{gray!10}{Ljung-Box} & \cellcolor{gray!10}{0.0211} & \cellcolor{gray!10}{0.8846} & \cellcolor{gray!10}{Pas d'autocorrélation}\\
Jarque-Bera & 101.6076 & 0.0000 & Normalité des résidus\\
\cellcolor{gray!10}{Breusch-Pagan} & \cellcolor{gray!10}{2.7860} & \cellcolor{gray!10}{0.4258} & \cellcolor{gray!10}{Homoscédasticité}\\
\bottomrule
\end{longtable}

\begin{longtable}[t]{llr}
\caption{\label{tab:unnamed-chunk-51}Facteurs d'inflation de la variance (VIF) - Fond propres Non-Vie}\\
\toprule
 & Variable & VIF\\
\midrule
\cellcolor{gray!10}{dplyr::lag(diff\_ratio, 1)} & \cellcolor{gray!10}{dplyr::lag(diff\_ratio, 1)} & \cellcolor{gray!10}{1.083}\\
dplyr::lag(diff\_taux\_court, 3) & dplyr::lag(diff\_taux\_court, 3) & 1.314\\
\cellcolor{gray!10}{dplyr::lag(diff\_taux\_long, 3)} & \cellcolor{gray!10}{dplyr::lag(diff\_taux\_long, 3)} & \cellcolor{gray!10}{1.321}\\
\bottomrule
\end{longtable}

\subsubsection{Modèle ARDL}\label{moduxe8le-ardl-1}

\begin{longtable}[t]{lrrrr}
\caption{\label{tab:unnamed-chunk-52}Modèle à Correction d'Erreur (Dynamique de Court Terme)}\\
\toprule
 & Estimate & Std. Error & t value & P value\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{5.98835} & \cellcolor{gray!10}{1.65040} & \cellcolor{gray!10}{3.62843} & \cellcolor{gray!10}{0.00167}\\
L(ratio, 1) & -1.43577 & 0.22933 & -6.26078 & 0.00000\\
\cellcolor{gray!10}{L(l\_ipc, 1)} & \cellcolor{gray!10}{-0.71122} & \cellcolor{gray!10}{0.51071} & \cellcolor{gray!10}{-1.39260} & \cellcolor{gray!10}{0.17903}\\
taux\_pib & -0.59514 & 0.42662 & -1.39501 & 0.17831\\
\cellcolor{gray!10}{L(d\_taux\_l, 1)} & \cellcolor{gray!10}{0.11224} & \cellcolor{gray!10}{0.06702} & \cellcolor{gray!10}{1.67463} & \cellcolor{gray!10}{0.10957}\\
\addlinespace
l\_sp & 0.65333 & 0.16876 & 3.87144 & 0.00095\\
\cellcolor{gray!10}{l\_cac} & \cellcolor{gray!10}{-0.55268} & \cellcolor{gray!10}{0.26657} & \cellcolor{gray!10}{-2.07330} & \cellcolor{gray!10}{0.05128}\\
d(L(ratio, 1)) & 0.36560 & 0.15397 & 2.37443 & 0.02770\\
\cellcolor{gray!10}{d(l\_ipc)} & \cellcolor{gray!10}{6.96610} & \cellcolor{gray!10}{3.24159} & \cellcolor{gray!10}{2.14898} & \cellcolor{gray!10}{0.04406}\\
d(L(l\_ipc, 1)) & -1.15610 & 3.03671 & -0.38071 & 0.70743\\
\addlinespace
\cellcolor{gray!10}{d(L(l\_ipc, 2))} & \cellcolor{gray!10}{13.40692} & \cellcolor{gray!10}{3.48527} & \cellcolor{gray!10}{3.84673} & \cellcolor{gray!10}{0.00101}\\
d(d\_taux\_l) & 0.02890 & 0.04920 & 0.58739 & 0.56352\\
\bottomrule
\end{longtable}

\begin{verbatim}
## R-squared: 0.7576 | Adjusted R-squared: 0.6243
\end{verbatim}

\textbf{Test d'absence d'autocorrélation des résidus :}

\begin{verbatim}

    Breusch-Godfrey test for serial correlation of order up to 4

data:  final_model
LM test = 9.4673, df = 4, p-value = 0.05042
\end{verbatim}

\textbf{Test de Normalité (Jarque-Bera)}

\begin{verbatim}

    Jarque Bera Test

data:  residus
X-squared = 2.0426, df = 2, p-value = 0.3601
\end{verbatim}

\textbf{Test de stabilité CUSUM et CUSUM Squared :} \textbackslash{}

\begin{flushleft}\includegraphics{Stat_desc_files/figure-latex/test 4 CUSUM-1} \end{flushleft}

\textbf{Diagnoctic visuel}

\begin{flushleft}\includegraphics{Stat_desc_files/figure-latex/diagnostic-1} \end{flushleft}

\subsection{Lecture et analyse des rapports annuels des compagnies
d'assurance}\label{lecture-et-analyse-des-rapports-annuels-des-compagnies-dassurance}

Dans cette partie, nous avons parcouru un ensemble de rapports sur la
solvabilité et la situation financière de plusieurs compagnies
d'assurance entre 2019 et 2025 afin d'approfondir la compréhension des
mécanismes par lesquels les variables macroéconomiques et
macro-financières affectent la solvabilité des assureurs. Nous nous
sommes concentrés uniquement sur les parties des rapports annuels qui
traitent de la solvabilité en nous focalisant sur :

\begin{itemize}
\tightlist
\item
  la variation des SCR, des fonds propres et des ratios de solvabilité ;
\item
  la variation des variables macro-financières.
\end{itemize}

Dans un second temps, nous avons mis ces évolutions en relation avec la
chronologie macroéconomique établie précédemment afin de mieux
comprendre le lien entre la conjoncture économique et la situation des
assureurs. Cette comparaison montre plusieurs éléments importants.
D'abord, l'inflation pénalise particulièrement les assureurs non-vie,
car elle augmente le coût des sinistres, des réparations et, plus
généralement, des charges techniques. Elle réduit donc leurs marges,
pèse sur le résultat net et peut aussi conduire à renforcer les
provisions. Les assureurs vie sont également touchés, mais de façon
différente : l'inflation diminue le rendement réel des placements et
rend certains produits d'épargne concurrents plus attractifs, ce qui
peut freiner la collecte et réduire la rentabilité des contrats.

Par ailleurs, cette analyse confirme que les taux d'intérêt jouent un
rôle central dans la solvabilité des assureurs. Lorsque les taux restent
bas, les placements obligataires rapportent moins et les engagements de
long terme deviennent plus contraignants, surtout en assurance vie. À
l'inverse, la remontée des taux peut alléger certaines charges
d'actualisation, mais elle peut aussi entraîner des pertes de valeur sur
les actifs détenus. Enfin, la volatilité des marchés financiers a elle
aussi un impact important, car elle agit à la fois sur la valeur des
actifs, sur les fonds propres et sur le capital requis. Ainsi, les
rapports annuels confirment que la solvabilité des assureurs dépend
fortement de l'environnement macro-financier, mais aussi de leur
exposition aux différents risques et de leur capacité à absorber les
chocs.

Ces éléments permettent d'apporter un premier éclairage sur la
problématique étudiée et d'orienter l'analyse statistique qui sera menée
par la suite, afin de faciliter l'interprétation des résultats.

\subsection{Détail des variables
qualitatives}\label{duxe9tail-des-variables-qualitatives}

\subsubsection{Nature}\label{nature}

Cette variable décrit l'activité d'assurance de la société :

\begin{itemize}
\tightlist
\item
  \textbf{Non Vie} : assurance dommages, automobile, habitation, santé,
  etc.
\item
  \textbf{Vie/Capitalisation} : assurance vie, épargne et
  capitalisation.
\item
  \textbf{Mixte} : compagnie présente à la fois sur les métiers Vie et
  Non-Vie.
\item
  \textbf{Réassurance} : activité de réassurance.
\item
  \textbf{FRPS} : fonds de retraite professionnelle supplémentaire.
\end{itemize}

Dans notre analyse, nous nous intéresserons seulement aux natures
\textbf{Non-Vie} et \textbf{Mixte}.

\subsubsection{Famille}\label{famille}

Cette variable classe les assureurs selon leur modèle d'organisation :

\begin{itemize}
\tightlist
\item
  \textbf{Mutualiste} : assureur détenu par ses sociétaires, sans
  actionnaires, dont les résultats sont principalement réinvestis au
  service des assurés.
\item
  \textbf{Traditionnel} : assureur organisé en société de capitaux,
  détenu par des actionnaires et orienté vers la rentabilité financière.
\item
  \textbf{Bancassureur} : assureur intégré à un groupe bancaire, qui
  distribue ses produits principalement via le réseau bancaire.
\end{itemize}

Cette distinction est utile pour comparer les profils de solvabilité,
car les contraintes financières et les sources de financement peuvent
différer selon le modèle.

\subsubsection{Remise}\label{remise}

Cette variable indique la périodicité de la donnée :

\begin{itemize}
\tightlist
\item
  \textbf{T1, T2, T3, T4} : remises trimestrielles ;
\item
  \textbf{A} : remise annuelle.
\end{itemize}

Dans le jeu de données, certaines années ne contiennent pas toutes les
remises, ce qui traduit simplement des différences de disponibilité des
données selon les périodes.

\subsection{Les formules du SCR}\label{les-formules-du-scr}

Le SCR (\emph{Solvency Capital Requirement}) représente l'exigence en
fonds propres permettant à un assureur de faire face à ses risques sur
un horizon d'un an avec une probabilité de 99,5 \%, soit l'équivalent
d'une faillite théorique tous les 200 ans. Les assureurs peuvent
utiliser la formule standard définie par l'EIOPA, un modèle interne
propre à leur structure de risque, ou une combinaison des deux (modèle
partiel). Le SCR se décompose en trois termes :

\[SCR = BSCR + SCR_{op} - Adj\]

Le BSCR (\emph{Basic SCR}) agrège les SCR par type de risque à l'aide
d'une matrice de corrélation. L'Adj représente la capacité d'absorption
des pertes par les provisions techniques et les impôts différés. Chaque
SCR élémentaire correspond à la perte de fonds propres résultant d'un
choc instantané calibré par l'EIOPA.

\[BSCR = \sqrt{\sum_{i,j} Corr_{i,j} \cdot SCR_i \cdot SCR_j} + SCR_{intangibles}\]

Les coefficients \(Corr_{i,j}\) de la formule du BSCR sont issus de la
matrice suivante :

\begin{longtable}[]{@{}lrrrrr@{}}
\toprule\noalign{}
& Marché & Défaut & Sous. Vie & Sous. Santé & Sous. Non-vie \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Marché & 1 & 0,25 & 0,25 & 0,25 & 0,25 \\
Défaut & 0,25 & 1 & 0,25 & 0,25 & 0,5 \\
Souscription Vie & 0,25 & 0,25 & 1 & 0,25 & 0 \\
Souscription Santé & 0,25 & 0,25 & 0,25 & 1 & 0 \\
Souscription Non-vie & 0,25 & 0,5 & 0 & 0 & 1 \\
\end{longtable}

\subsubsection{Risque de souscription}\label{risque-de-souscription}

Le risque de souscription couvre l'incertitude sur les résultats des
contrats, due notamment à des erreurs de tarification, de
provisionnement ou à la survenance d'événements extrêmes. Il se divise
en trois modules distincts, chacun calculé par agrégation matricielle de
ses propres sous-risques :

\[SCR_{vie} = \sqrt{\sum_{(i,j)} Corr^{Vie}_{i,j} \cdot SCR_i \cdot SCR_j}\]

\[SCR_{sant\acute{e}} = \sqrt{\sum_{(i,j)} Corr^{Sant\acute{e}}_{i,j} \cdot SCR_i \cdot SCR_j}\]

\[SCR_{non-vie} = \sqrt{\sum_{(i,j)} Corr^{NV}_{i,j} \cdot SCR_i \cdot SCR_j}\]

La matrice \(Corr^{Vie}\) pour le risque vie comprend sept sous-risques.
Les corrélations négatives, par exemple entre mortalité et longévité
(−0,25), reflètent leur nature opposée : une hausse de la mortalité est
défavorable pour les contrats décès mais favorable pour les rentes
viagères, ce qui justifie une compensation partielle dans le calcul du
SCR.

\subsubsection{Matrice des sous-risques
vie}\label{matrice-des-sous-risques-vie}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0968}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1290}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1290}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1290}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1290}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1290}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1290}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1290}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Mortalité
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Longévité
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Invalidité
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Dépenses
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Révision
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Cessation
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Catastrophe
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Mortalité & 1 & -0,25 & 0,25 & 0,25 & 0 & 0 & 0,25 \\
Longévité & -0,25 & 1 & 0 & 0,25 & 0,25 & 0,25 & 0 \\
Invalidité & 0,25 & 0 & 1 & 0,5 & 0 & 0 & 0,25 \\
Dépenses & 0,25 & 0,25 & 0,5 & 1 & 0,5 & 0,5 & 0,25 \\
Révision & 0 & 0,25 & 0 & 0,5 & 1 & 0 & 0 \\
Cessation & 0 & 0,25 & 0 & 0,5 & 0 & 1 & 0,25 \\
Catastrophe & 0,25 & 0 & 0,25 & 0,25 & 0 & 0,25 & 1 \\
\end{longtable}

\subsubsection{Risque de marché}\label{risque-de-marchuxe9}

Le risque de marché mesure la sensibilité de l'assureur aux évolutions
des marchés financiers (taux, actions, immobilier, devises, spreads). Il
est calculé par agrégation matricielle de six sous-risques :

\[SCR_{march\acute{e}} = \sqrt{\sum_{(i,j)} Corr^{March\acute{e}}_{i,j} \cdot SCR_i \cdot SCR_j}\]

\begin{longtable}[]{@{}lrrrrrr@{}}
\toprule\noalign{}
& Taux & Actions & Immobilier & Spread & Concentration & Devise \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Taux d'intérêt & 1 & A & A & A & 0 & 0,25 \\
Actions & A & 1 & 0,75 & 0,75 & 0 & 0,25 \\
Immobilier & A & 0,75 & 1 & 0,5 & 0 & 0,25 \\
Spread & A & 0,75 & 0,5 & 1 & 0 & 0,25 \\
Concentration & 0 & 0 & 0 & 0 & 1 & 0 \\
Devise & 0,25 & 0,25 & 0,25 & 0,25 & 0 & 1 \\
\end{longtable}

Le paramètre \(A\) vaut 0 si \(SCR_{taux}\) est issu d'un choc à la
hausse, 0,5 sinon.

\subsubsection{Détail des formules et chocs par
sous-risque}\label{duxe9tail-des-formules-et-chocs-par-sous-risque}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 2\tabcolsep) * \real{0.5000}}
  >{\raggedright\arraybackslash}p{(\linewidth - 2\tabcolsep) * \real{0.5000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Sous-risque
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Formule / Choc
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Actions & \(SCR_{actions}\) dépend du choc sur les actions selon leur
nature, avec un niveau différent pour les actions cotées, non cotées et
l'infrastructure éligible. Un ajustement symétrique vient moduler ce
choc. \\
Spread & Hausse des spreads appliquée aux obligations, prêts,
titrisations et dérivés de crédit. L'intensité du choc dépend de la
notation de l'émetteur et de la duration de la créance. \\
Taux d'intérêt & Chocs de hausse et de baisse des taux, plus élevés à
court terme puis décroissants linéairement avec l'échéance. Les valeurs
intermédiaires sont obtenues par interpolation. \\
Change & Choc de ±25 \% sur les devises étrangères par rapport à la
monnaie locale. Le SCR retenu correspond au scénario le plus défavorable
entre hausse et baisse. \\
Immobilier & Choc de −25 \% sur la valeur de marché de l'ensemble des
actifs immobiliers détenus. \\
Concentration & Mesure du risque lié à une exposition trop importante
sur une même signature. Le calcul dépend du ratio de solvabilité de
l'entreprise et de la qualité de crédit des contreparties. \\
\end{longtable}

\subsubsection{Risque de défaut de
contrepartie}\label{risque-de-duxe9faut-de-contrepartie}

Ce risque couvre la perte potentielle liée à la défaillance d'une
contrepartie. Il se distingue du risque de spread, qui concerne la
dégradation de la qualité de crédit des émetteurs de valeurs mobilières,
et concerne exclusivement :

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 2\tabcolsep) * \real{0.5000}}
  >{\raggedright\arraybackslash}p{(\linewidth - 2\tabcolsep) * \real{0.5000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Contrepartie
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Description
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Réassureurs & Défaut d'un réassureur sur ses engagements de couverture
envers le cédant. C'est l'une des expositions les plus significatives
pour les assureurs ayant fortement externalisé leur risque. \\
Banques dépositaires & Défaut d'un établissement bancaire détenant les
actifs en dépôt. Cela concerne directement la valeur liquidative du
portefeuille d'investissements de l'assureur. \\
Autres débiteurs & Intermédiaires d'assurance, preneurs, montants à
recevoir au titre des créances sur contrats. Cela comprend aussi les
débiteurs au titre des procédures de recours et subrogations. \\
\end{longtable}

Dans la matrice BSCR, le risque de défaut présente une corrélation de
0,25 avec tous les autres modules, à l'exception de la souscription
non-vie avec laquelle la corrélation est portée à 0,5, reflétant
l'interdépendance entre la sinistralité et les défauts de réassureurs.

\end{document}
